project_id = "kvrxgaxjdpxqlnfhhsrc"

[functions.daily-waste-notifications]
verify_jwt = false

[functions.send-auth-email]
verify_jwt = false

[functions.send-interest-notification]
verify_jwt = false

[functions.notify-admins-new-offer]
verify_jwt = false