-- Import all street names from the uploaded file
INSERT INTO public.streets (name) VALUES 
('Adolf-Damaschke-Straße'),
('Agathastraße'),
('Agnes-Decker-Straße'),
('Ahornweg'),
('Akazienweg'),
('Alte Bohle'),
('Alte Bonnstraße'),
('Am Amtsgericht'),
('Am Birkhof'),
('Am Daberger Hof'),
('Am Eichenbusch'),
('Am Falter'),
('Am Hennebach'),
('Am Hohlweg'),
('Am Hülderberg'),
('Am Inselweiher'),
('Am Kirchberg'),
('Am Krausen Baum'),
('Am Kreuz'),
('Am Kuttenbusch'),
('Am Michelshof'),
('Am Mühlenhof'),
('Am Pappelbusch'),
('Am Pastorsgarten'),
('Am Petershof'),
('Am Rankewerk'),
('Am Rheindorfer Bach'),
('Am Ringofen'),
('Am Rolfsacker'),
('Am Römerkanal'),
('Am Rott'),
('Am Siegesbach'),
('Am Strauchshof'),
('Am Volkspark'),
('An Der Alten Brauerei'),
('An der Alten Zuckerfabrik'),
('An der Bleiche'),
('An der Brücke'),
('An der Hohlen Gasse'),
('An der Kapelle'),
('An der Linde'),
('An der Schallenburg'),
('An der Synagoge'),
('An der Ville-Bahn'),
('An der Ziegelei'),
('An Haus Vendel'),
('An Hornsgarten'),
('An Maria Glück'),
('An Schloss Falkenlust'),
('Andreaskirchplatz'),
('Anna-Schmitz-Straße'),
('Anna-Seghers-Straße'),
('Anne-Frank-Straße'),
('Anton-Ockenfels-Straße'),
('Arminiusweg'),
('Arndtstraße'),
('Auf Dem Gallberg'),
('Auf dem Kamm'),
('Auf den Steinen'),
('Auf der Höhe'),
('Auf Der Kehre'),
('Auf der Pehle'),
('Auguste-Viktoria-Straße'),
('Badorfer Straße'),
('Bahnhofstraße'),
('Balthasar-Neumann-Platz'),
('Barbarastraße'),
('Bavinganstraße'),
('Belvedere'),
('Bendgespfad'),
('Bergerstraße'),
('Berggasse'),
('Berggeiststraße'),
('Bergstraße'),
('Berliner Ring'),
('Berrenrather Straße'),
('Bertolt-Brecht-Straße'),
('Berzdorfer Straße'),
('Bettina-Von-Arnim-Straße'),
('Bitterfelder Straße'),
('Bleibtreuseeweg'),
('Böningergasse'),
('Bonnstraße'),
('Bootsweg'),
('Brauweilerweg'),
('Bremer Straße'),
('Breslauer Straße'),
('Brückenstraße'),
('Buchenweg'),
('Burgpfad'),
('Burgstraße'),
('Buschgasse'),
('Cäcilienstraße'),
('Carl-Schurz-Straße'),
('Caspar-Markard-Straße'),
('Chiapas'),
('Chlodwigstraße'),
('Clemens-August-Straße'),
('Comesstraße'),
('Cottbuser Weg'),
('Daberger Höhe'),
('Daberger Weg'),
('Danziger Straße'),
('Donatusstraße'),
('Drachenfelsstraße'),
('Dreichtenweg'),
('Dresdener Straße'),
('Dunkelallee'),
('Eckdorfer Mühlenweg'),
('Eckdorfer Straße'),
('Edelgasse'),
('Eibenweg'),
('Eichendorffstraße'),
('Eichweg'),
('Eifelstraße'),
('Elisabethstraße'),
('Elsterpfad'),
('Engeldorfer Straße'),
('Erich-Kästner-Straße'),
('Erlengrund'),
('Eselsallee'),
('Euskirchener Straße'),
('Falkenluster Allee'),
('Falkenweg'),
('Ferdinand-Krausen-Weg'),
('Fischenicher Straße'),
('Fischmarkt'),
('Flechtenweg'),
('Frankenstraße'),
('Franz-von-Kesseler-Straße'),
('Franziskanerhof'),
('Franzstraße'),
('Frechener Straße'),
('Fredenbruch'),
('Freiheitstraße'),
('Freiherr-vom-Stein-Straße'),
('Friederikeweg'),
('Friedrich-Ebert-Straße'),
('Friedrichstraße'),
('Fritz-Wündisch-Straße'),
('Fronhofweg'),
('Fuchsstraße'),
('Gabriele-Münter-Weg'),
('Gartenstraße'),
('Gebrüder-Grimm-Straße'),
('Geildorfer Bach'),
('Geildorfer Straße'),
('Georg-Großer-Straße'),
('Georg-Grosser-Straße'),
('Georg-Sandmann-Straße'),
('Gertrudenstraße'),
('Ginsterhang'),
('Gleueler Weg'),
('Glizmudisstraße'),
('Godorfer Straße'),
('Goethestraße'),
('Gottfried-Keller-Straße'),
('Grubenstraße'),
('Gruhlstraße'),
('Grünebergstraße'),
('Grüner Weg'),
('Günter-Krüger-Straße'),
('Gustav-Wegge-Straße'),
('Hainbuchenweg'),
('Halfenweg'),
('Hamburger Straße'),
('Hannah-Arendt-Straße'),
('Härriskuhl'),
('Hauptstraße'),
('Hedwig-Gries Straße'),
('Hedwig-Gries-Straße'),
('Heider Bergsee'),
('Heinestraße'),
('Heinrich-Esser-Straße'),
('Heinrich-Fetten-Platz'),
('Heinrich-Kreutzberg-Straße'),
('Heinrich-Lierz-Straße'),
('Heinrich-Spoerl-Straße'),
('Helma-Meyers-Straße'),
('Hennersweg'),
('Hermann-Faßbender-Straße'),
('Hermann-Gruhl-Straße'),
('Hermann-Löns-Straße'),
('Hermannstraße'),
('Hermülheimer Straße'),
('Herseler Straße'),
('Himmelreich'),
('Hochstraße'),
('Höhenweg'),
('Hommelsheimstraße'),
('Hospitalstraße'),
('Hubert-Geuer-Straße'),
('Hubertusstraße'),
('Hüllenweg'),
('Hürther Straße'),
('Ida-Ehre-Weg'),
('Im Bungarten'),
('Im Klostergarten'),
('Im Mühlengrund'),
('Im Paradies'),
('Im Sonntagsgarten'),
('Im Vogelsang'),
('Immendorfer Straße'),
('In der Maar'),
('In Der Schleide'),
('Irmgard-Keun-Weg'),
('Jakob-Sonntag-Straße'),
('Janshof'),
('Janshofpassage'),
('Jordanstraße'),
('Josef-Burfeid-Weg'),
('Josef-Flohr-Weg'),
('Josef-Hürten-Straße'),
('Josef-Von-Görres-Str.'),
('Josef-von-Görres-Straße'),
('Josefstraße'),
('Joseph-Hürten-Straße'),
('Joseph-Von-Görres-Straße'),
('Jülichsgasse'),
('Junkersdorfer Weg'),
('Kaiserstraße'),
('Kämperpfad'),
('Kapellenweg'),
('Kastanienweg'),
('Kempishofstraße'),
('Kentenichstraße'),
('Kierberger Straße'),
('Kirchgasse'),
('Kirchstraße'),
('Kirchweg'),
('Kleiststraße'),
('Kloster Benden'),
('Klosterstraße'),
('Knappschaftsstraße'),
('Kölnstraße'),
('Kolpingplatz'),
('Königsberger Straße'),
('Königsdorfer Weg'),
('Königstraße'),
('Konrad-Adenauer-Straße'),
('Kreuzhof'),
('Kuhgasse-Eckdorf'),
('Kunibertweg'),
('Kurfürstenstraße'),
('Langenackerstraße'),
('Laurentiusweg'),
('Leamington-Spa-Platz'),
('Leipziger Straße'),
('Lennéstraße'),
('Lenterbachsweg'),
('Lessingstraße'),
('Letterhausstraße'),
('Liblarer Straße'),
('Lida-Gustava-Heymann-Straße'),
('Lindenhof'),
('Lindenstraße'),
('Lise-Meitner-Straße'),
('Lohmühle'),
('Lohrbergstraße'),
('Louise-Straus-Straße'),
('Lövenicher Straße'),
('Löwenburgstraße'),
('Lucretiaweg'),
('Ludwig-Jahn-Straße'),
('Ludwig-Uhland-Straße'),
('Luisenstraße'),
('Lupinenweg'),
('Maiglerstraße'),
('Maja-Lex-Weg'),
('Margaretenstraße'),
('Margarethe-von-Hersel-Straße'),
('Marie-Curie-Straße'),
('Marie-Schlei-Straße'),
('Marienstraße'),
('Markt'),
('Mascha-Kaleko-Straße'),
('Matthäusstraße'),
('Max-Ernst-Allee'),
('Maximilian-Franz-Straße'),
('Mayersweg'),
('Merricher Straße'),
('Merseburger Straße'),
('Mertener Straße'),
('Metzenmacherweg'),
('Mittelstraße'),
('Mönengasse'),
('Mühlenbach'),
('Mühlenberg'),
('Mühlenstraße'),
('Neue Bohle'),
('Neue Königstraße'),
('Niklaus-Ehlen-Straße'),
('Nikolaus-Ehlen-Straße'),
('Nußbaumweg'),
('Obermühle'),
('Oberstraße'),
('Oelbergstraße'),
('Otto-Paes-Straße'),
('Otto-Wels-Straße'),
('Palmersdorfer Hof'),
('Pantaleonstraße'),
('Parkstraße'),
('Pastoratstraße'),
('Paul-Dahm-Straße'),
('Pehler Feldchen'),
('Pehler Hülle'),
('Peter-Schmitter-Straße'),
('Petersbergstraße'),
('Peterstraße'),
('Pfarrer-Robert-Grosche-Straße'),
('Phantasialandstraße'),
('Pingsdorfer Straße'),
('Platanenallee'),
('Platanenweg'),
('Poppelsdorfer Allee'),
('Poststraße'),
('Pulheimer Straße'),
('Pützgasse'),
('Reihe 9-Eckdorf'),
('Renault-Nissan-Straße'),
('Rheinstraße'),
('Ricarda-Huch-Weg'),
('Richard-Bertram-Straße'),
('River Quest-Eckdorf'),
('Robertsstraße'),
('Rodderweg'),
('Roisdorfer Straße'),
('Römerhof'),
('Römerstraße'),
('Rondorfer Straße'),
('Rösberger Straße'),
('Rosenhof'),
('Schiffergasse'),
('Schildgesstraße'),
('Schillerstraße'),
('Schlaunstraße'),
('Schloß Augustusburg'),
('Schloßstraße'),
('Schnorrenberg'),
('Schöffenstraße'),
('Schulstraße'),
('Schultheißstraße'),
('Schützenstraße'),
('Schwarzer Weg'),
('Schwestern-Brünell-Weg'),
('Sechtemer Straße'),
('Seeweg'),
('Senecaweg'),
('Senftenberger Straße'),
('Servatiusstraße'),
('Severinstraße'),
('Sophie-Scholl-Straße'),
('Sophienstraße'),
('Spielmannsgasse-Eckdorf'),
('Spremberger Weg'),
('Spürckstraße'),
('St.-Albert-Straße'),
('St.Albert-Straße'),
('Steingasse'),
('Steinkleehang'),
('Steinweg'),
('Stephanstraße'),
('Stettiner Straße'),
('Stiftstraße'),
('Stommelner Weg'),
('Stotzheimer Weg'),
('Sürther Straße-Rodenkirchen'),
('Tacitusweg'),
('Tafelhofstraße'),
('Talstraße'),
('Taunusstraße'),
('Theismühle'),
('Theodor-Heuss-Straße'),
('Theodor-Körner-Straße'),
('Theodor-Storm-Straße'),
('Thüringer Platz'),
('Tiergartenstraße'),
('Töpfergasse'),
('Ubierstraße'),
('Uhlstraße'),
('Ulmenweg'),
('Unter Birken'),
('Unter dem Dorf'),
('Unter Eschen'),
('Untermühle'),
('Urfelder Straße'),
('Ursulastraße'),
('Villestraße'),
('Vochemer Straße'),
('Volkwinsweg'),
('Von-Droste-Hülshoff-Straße'),
('Von-Heinsberg-Straße'),
('Von-Hessen-Straße'),
('Von-Holte-Straße'),
('Von-Lupenau-Straße'),
('Von-Roll-Straße'),
('Von-Westerburg-Straße'),
('Von-Wied-Straße'),
('Vorgebirgsstraße'),
('Walberberger Straße'),
('Waldorfer Straße'),
('Waldweg'),
('Waldweg Route A6'),
('Wallstraße'),
('Wasserturmweg'),
('Wehrbachsweg'),
('Weiherhofstraße'),
('Weilerhof'),
('Weilerstraße'),
('Weißer Straße'),
('Wesselinger Straße'),
('Weyhestraße'),
('Wilhelm-Busch-Straße'),
('Wilhelm-Kamm-Straße'),
('Wilhelmstraße'),
('Will-Küpper-Straße'),
('Willy-Brandt-Straße'),
('Wingertsberg'),
('Winterburg'),
('Wittelsbacherstraße'),
('Wolfsgasse'),
('Wolkenburgstraße'),
('Xavier-Kürten-Weg'),
('Ziegelweg'),
('Zum Donnerbach'),
('Zum Herrengarten'),
('Zum Rodderbruch'),
('Zum Schützenplatz'),
('Zum Sommersberg'),
('Zur Gabjei')
ON CONFLICT (name) DO NOTHING;