// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kvrxgaxjdpxqlnfhhsrc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt2cnhnYXhqZHB4cWxuZmhoc3JjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MzE1MTMsImV4cCI6MjA3NDQwNzUxM30.MmbnGDJMdoYHfupos8blS_pqAukS5r9A3-nzuKdsLkY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});